<?php
/**
 * @file
 * Installation of this module.
 */

/**
 * Implements hook_schema().
 * to include table haplotypemap_files in DB with keys and indexes
 */
function haplotypembed_schema(){
  $schema = array();

  $schema['haplotypembed_files'] = array(
    'description' => 'Keeps track of haplotype map files for embeded module haplotype-map',
    'fields' => array(
      'haplotypembed_file_id' => array(
        'description' => 'Primary Key',
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'file_path' => array(
        'description' => 'Absolute path to an existing haplotype map file.',
        'type' => 'text',
        'not null' => TRUE,
      ),
      'default_file_path' => array(
        'description' => 'Absolute path to an existing default haplotype map file.',
        'type' => 'text',
        'not null' => TRUE,
      ),
      'description' => array(
        'description' => 'Free text description of the haplotype map file.',
        'type' => 'text',
      ),
      'human_readable_name' => array(
        'description' => 'Human-readable name for the haplotype map file.',
        'type' => 'varchar',
        'length' => 200,
        'not null' => TRUE,
      ),
      'all_germplasm' => array(
        'description' => 'Free text includes all germplasm names of the haplotype map file.',
        'type' => 'text',
      ),
      'default_germplasm' => array(
        'description' => 'Free text includes dafault germplasm names of the haplotype map file.',
        'type' => 'text',
      ),
    ),
    'primary key' => array('haplotypembed_file_id'),
  );

  $schema['haplotypembed_perm'] = array(
    'description' => 'Keeps track of permissions for embeded haplotype map files.',
    'fields' => array(
      'haplotypembed_file_perm_id' => array(
        'description' => 'Primary Key',
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'haplotypembed_file_id' => array(
        'description' => 'Links to the VCF files',
        'type' => 'int',
        'not null' => TRUE,
      ),
      'rid' => array(
        'description' => 'The ROLE ID of a role to provide access to.',
        'type' => 'int',
      ),
      'uid' => array(
        'description' => 'The USER ID of a user to provide access to.',
        'type' => 'int',
      ),
    ),
    'primary key' => array('haplotypembed_file_perm_id'),
  );

  return $schema;
}
