<?php
/**
 *
 * The main functionality of this module.
 * Embed module haplotype-map to visualize haplotype data in tripal sites.
 *
 * about haplotype-map:
 * developed by Venkat Bandi(https://github.com/kiranbandi)
 * the module is available in https://github.com/kiranbandi/haplotype-map
*/
/**
 * Implements hook_menu(). 1
 */
function haplotypembed_menu(){
  // $default_map = NULL;
  //
  // //get all
  // $h_maps = haplotype_extract_available_maps(, );

  // $items['haplotype-map'] = array(
  //   'title' => t('Haplotype data Visulization')，
  //   'page callback' => 'page_list_available_maps',
  //   'access arguments' => array('view haplotype map'),
  //   'type' => MENU_NORMAL_ITEM,
  // );
  $items = array();

  $items['haplotype-map_embed'] = array(
    'title' => 'Haplotype Maps',
    'description' => 'Embeded haplotype map module for users to view haplotype files.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('haplotypemap_embed_form'),
    'access callback' => TRUE,
  );

  //administration
  //manage files, list
  $items['admin/tripal/extension/haplotype-map_embed'] = array(
    'title' => 'Embeded Haplotype map',
    'description' => 'Provides users embeded haplotype maps.',
    'page callback' => 'haplotypemap_embed_admin_list',
    'page arguments' => array(),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/haplotype-map_embed.admin.inc',
  );
  // add
  $items['admin/tripal/extension/haplotype-map_embed/add'] = array(
    'title' => 'Add Haplotype map',
    'description' => 'Add a haplotype map in list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('haplotypemap_embed_admin_file_form', 'add'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/haplotype-map_embed.admin.inc',
  );
  // edit
  $items['admin/tripal/extension/haplotype-map_embed/edit'] = array(
    'title' => 'Edit Haplotype map',
    'description' => 'Edit a haplotype map in list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('haplotypemap_embed_admin_file_form', 'edit'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/haplotype-map_embed.admin.inc',
  );
  // delete
  $items['admin/tripal/extension/haplotype-map_embed/delete'] = array(
    'title' => 'Delete Haplotype map',
    'description' => 'Delete a haplotype map in list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('haplotypemap_embed_admin_file_form', 'delete'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/haplotype-map_embed.admin.inc',
  );


  // manage access

  return $items;
}



//  /**
//  * Implements hook_permission().2
//  */
//
// function haplotypembed_permission(){
//   return array(
//     'view haplotype map' => array(
//       'title' => t('Access Public Haplotype maps.'),
//     ),
//     'view private haplotype map' => array(
//       'title' => t('Access Private Haplotype maps.'),
//     ),
//   );
//
// }


 /**
  * Implements hook_libraries_info(). last
  */
  function haplotypembed_libraries_info(){
    $libraries['haplotype-map'] = array(
      'name' => 'haplotype-map',
      'vendor url' => 'https://github.com/kiranbandi/haplotype-map',
      'version' => '0.0.1',
      'download url' => ,'https://github.com/kiranbandi/haplotype-map'
    );
    return $libraries;
  }

// <html lang="en">
//   <head><meta charset="utf-8">
//   <meta http-equiv="X-UA-Compatible" content="IE=edge">
//   <meta name="viewport" content="width=device-width,initial-scale=1">
//   <meta name="description" content="Haplotype Visualization Browser developed at University of Saskatchewan">
//   <meta name="author" content="kiranbandi">
//   <title>SNPs Haplotype Visualization</title>
//   <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet"></head>
//     <body>
//       <div id="root"></div>
//       <script src="bundle/main.bundle.1cd727076111f0e998e1.js"></script>
//     </body>
// </html>

/**
* Implements hook_form().
*/
function haplotypemap_embed_form($form, &$form_state){
  // check for available dataset, ask user to pick and feed to haplotype-map
  //section 1, ask user to select a file first
  $maps = page_list_available_maps();


  //section 2, give option of using default file or filter for specific germplasm
  //S2.a include haplotype-map using default file

  //S2.b filter file for the germpasm user choose then display with haplotype map viewer


  return $form;
}

 /**
  *  a mark-up to list all the available haplotype maps.
  */

function page_list_available_maps(){
  $output = '';

  return $output;
}
