<?php
  /**
   * @file
   * Installation of this module.
   */

  /**
   * Implements hook_schema().
   * to include table haplotypemap_files in DB with keys and indexes
   */

   function haplotypembed_files_schema(){
     $schema = array();

     $schema['haplotypembed_files'] = array(
       'description' => 'Keeps track of haplotype map files for embeded module haplotype-map',
       'fields' => array(
         'haplotypembed_file_id' => array(

         ),
         'file_path' => array(

         ),
         'default_file_path' => array(

         ),
         'description' => array(

         ),
         'human_readable_name' => array(

         ),
         'all_germplasm' => array(

         ),
         'default_germplasm' => array(

         ),
       ),
       'primary key' => array('haplotypembed_files_id'),

     );

     $schema['haplotypembed_perm'] = array(
       'description' => 'Keeps track of permissions for embeded haplotype map files.',
       'fields' => array(
         'haplotypembed_file_perm_id' => array(
           'description' => 'Primary Key',
           'type' => 'serial',
           'not null' => TRUE,
         ),
         'haplotypembed_file_id' => array(
           'description' => 'Links to the VCF files',
           'type' => 'int',
           'not null' => TRUE,
         ),
         'rid' => array(
           'description' => 'The ROLE ID of a role to provide access to.',
           'type' => 'int',
         ),
         'uid' => array(
           'description' => 'The USER ID of a user to provide access to.',
           'type' => 'int',
         ),
       ),
       'primary key' => array('haplotypembed_file_perm_id'),
     );

     return $schema;
   }
